[tool.black]
line-length = 88
target-version = ['py38']
include = '''
(
    files/jenky-tools
  | \.pyi?$
)
'''
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.typing_modules
  | \.?venv
  | _build
  | build
  | dist
)/
'''
